# SITE CONFIGURATION
title: уБлозе # your site title
titlefooter: У блозе 
author: Максим Севелев-Дубровник # You :P
description: > # Meta description of Homepage
  Максим Севелев-Дубровник: блог. Про белорусскость, 
  языкознание, современность и минувшее, про научно-исследовательский
  подход. Тексты песен на разных языках.
baseurl: "/ublozie" # the subpath of your site, e.g. /blog
url: "https://seveleu.com" # the base hostname & protocol for your site, e.g. http://example.com
theme: jekyll-sleek
lang: be

# SEO PLUGIN
social:
  name: Максим Севелев-Дубровник
  links:
    - https://eo.wikipedia.org/wiki/Maxime_Seveleu-Dubrovnik
    - https://www.amazon.com/Maxime-Seveleu-Dubrovnik/e/B087QW5VF8
#    - https://www.linkedin.com/in/BenBalter
#    - https://plus.google.com/+BenBalter
#    - https://github.com/benbalter
#    - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'уБлозе', link: '/'}
  - {name: 'Да праектаў', link: 'https://seveleu.com'}
  - {name: 'Сувязь', link: '/contact'}

tagline: >
  Беларускасць, вывучэнне моў, постмадэрн, навука, станоўчая памяркоўнасць, тэксты песень.

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: seveleu.dubrovnik@fias.fr # email for form submission

#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
#github_username:  janczizikow # replace with your_github_username or comment to remove link from footer
#instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

#disqus:
#  shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
